In [113]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from matplotlib.ticker import PercentFormatter

df_desordenado = pd.read_csv('../data/fantasy_data.csv')
df_desordenado = df_desordenado.drop(["PPGTarget_half-ppr","PointsTarget_half-ppr","Player","Key"], axis=1)

In [114]:
df_ordenado = df_desordenado.sort_values('Year')
df_ordenado = df_ordenado[~df_ordenado['Year'].between(1970, 1999)]
df_ordenado

,Tm,Pos,Age,G,GS,Pass_Cmp,Pass_Att,Pass_Yds,Pass_TD,Pass_Int,...,PPG_half-ppr,PPT_half-ppr,PointsOvrRank_half-ppr,PointsPosRank_half-ppr,PPGOvrRank_half-ppr,PPGPosRank_half-ppr,PPTOvrRank_half-ppr,PPTPosRank_half-ppr,Points_VORP_half-ppr,PPG_VORP_half-ppr
12838,BAL,WR,30,15,13,0,0,0,0,0,...,8.000000,2.448980,105,42,122,42,55,41,-16.00,-1.443750
9035,SFO,QB,30,16,16,355,561,4278,31,10,...,21.782500,0.550585,4,2,4,2,364,6,142.08,7.216250
25833,WAS,WR,23,4,0,0,0,0,0,0,...,0.000000,0.000000,470,164,470,164,470,164,-136.00,-9.443750
23353,WAS,TE,25,15,6,0,0,0,0,0,...,1.600000,2.666667,287,44,327,47,38,10,-52.90,-3.406250
5027,DEN,RB,22,9,0,0,0,0,0,0,...,2.588889,0.423636,290,90,273,81,399,133,-105.50,-6.861111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16849,TEN,WR,27,1,0,0,0,0,0,0,...,11.400000,11.400000,396,155,92,29,2,2,-149.80,0.394118
16766,TEN,TE,25,5,2,0,0,0,0,0,...,0.220000,1.100000,515,110,509,104,298,96,-111.30,-7.797647
16736,LVR,WR,24,7,1,0,0,0,0,0,...,0.800000,1.866667,447,175,439,175,171,125,-155.60,-10.205882
17679,CIN,TE,25,2,0,0,0,0,0,0,...,0.000000,0.000000,541,116,541,116,541,116,-112.40,-8.017647
29368,DET,TE,28,12,1,0,0,0,0,0,...,0.225000,2.700000,482,101,508,103,33,7,-109.70,-7.792647

In [115]:
df_ordenado["Year"]

12838    2000
9035     2000
25833    2000
23353    2000
5027     2000
         ...
16849    2024
16766    2024
16736    2024
17679    2024
29368    2024
Name: Year, Length: 14893, dtype: int64

In [116]:
df_ordenado["games_played_pct"] = df_ordenado["games_played_pct"]
df_ordenado["games_played_pct"].value_counts()

games_played_pct
1.000000    4319
0.937500    1212
0.875000     904
0.812500     682
0.062500     673
0.750000     559
0.125000     549
0.187500     484
0.687500     466
0.625000     464
0.500000     452
0.312500     429
0.250000     428
0.437500     415
0.375000     409
0.562500     384
0.941176     268
0.882353     193
0.058824     175
0.117647     141
0.823529     136
0.764706     132
0.176471     129
0.705882     124
0.647059      99
0.529412      99
0.470588      98
0.294118      96
0.588235      93
0.352941      90
0.235294      90
0.411765      84
0.000000      13
1.062500       3
1.058824       1
Name: count, dtype: int64

In [117]:
df_ordenado[df_ordenado["games_played_pct"] == 1.06250]

,Tm,Pos,Age,G,GS,Pass_Cmp,Pass_Att,Pass_Yds,Pass_TD,Pass_Int,...,PPG_half-ppr,PPT_half-ppr,PointsOvrRank_half-ppr,PointsPosRank_half-ppr,PPGOvrRank_half-ppr,PPGPosRank_half-ppr,PPTOvrRank_half-ppr,PPTPosRank_half-ppr,Points_VORP_half-ppr,PPG_VORP_half-ppr
22593,2TM,WR,28,17,0,0,0,0,0,0,...,0.000000,0.00000,514,170,514,170,514,170,-154.8,-10.550000
21925,2TM,WR,42,17,14,0,0,0,0,0,...,4.464706,2.53000,162,68,224,82,68,48,-78.9,-6.085294
22949,2TM,WR,32,17,16,1,1,35,1,0,...,9.135294,2.31791,92,33,136,46,105,83,-3.3,-1.983456

In [118]:
def resumen_nulos(df):
    nulos = df.isnull().sum()
    porcentaje = (nulos / len(df)) * 100
    resumen = pd.DataFrame({
        'Columna': df.columns,
        'Nulos': nulos.values,
        'Porcentaje_Nulos': porcentaje.values
    })
    return resumen.sort_values('Nulos', ascending=False)

# usamos nuestra función
print(resumen_nulos(df_ordenado))

df_ordenado = df_ordenado.drop(['PPGTarget_half-ppr','PointsTarget_half-ppr'], axis=1)

print(resumen_nulos(df_ordenado))

              Columna  Nulos  Porcentaje_Nulos
0                  Tm      0               0.0
46       Fmb_per_game      0               0.0
33         Rec_Catch%      0               0.0
34  Pass_Cmp_per_game      0               0.0
35  Pass_Att_per_game      0               0.0
..                ...    ...               ...
25          num_games      0               0.0
26   games_played_pct      0               0.0
27  games_started_pct      0               0.0
28            ProBowl      0               0.0
61  PPG_VORP_half-ppr      0               0.0

[62 rows x 3 columns]

KeyError: "['PPGTarget_half-ppr', 'PointsTarget_half-ppr'] not found in axis"